import logo from '@/assets/images/logo.jpg'
import signup from '@/assets/images/signup.jpg'
import login from '@/assets/images/login.jpg'
import box from '@/assets/images/box.png'
import noImage from '@/assets/images/no-image-found.jpg'

export const images = {
    logo,
    signup,
    login,
    box,
    noImage
}

// constants/translations.js
export const translations = {
    en: {
        websiteName: "CountryRise",
        dashboard: "Dashboard",
        products: "Products",
        product: "Product",
        price: "Price",
        salesOverview: "Sales Overview",
        myCourses: "My Courses",
        enrolledCourses: "Enrolled Courses",
        exploreCourses: "Explore Courses",
        offeredCourses: "Offered Courses",
        accountSettings: "Account Settings",
        signOut: "Sign Out",
        profile: "Profile",
        editProfile: "Edit Profile",
        saveChanges: "Save Changes",
        cancel: "Cancel",
        delete: 'Delete',
        edit: 'Edit',
        profileNoFileChosen: "No file chosen",
        personalInformation: "Personal Information",
        name: "Name",
        phone: "Phone",
        email: "Email",
        addressInformation: "Address Information",
        address: "Address",
        province: "Province",
        city: "City",
        noCourseFound: 'No courses found.',
        searchCourseByTitle: 'Search course by title...',
        createCourse: 'Create Course',
        deleteCourseConfirmation: 'Are you sure you want to delete course',
        totalSales: 'Total Sales',
        totalReviews: 'Total Reviews',
        rating: 'Rating',
        averageRating: 'Average Rating',
        mostSoldProduct: 'Most Sold Product',
        revenueGenerated: 'Revenue Generated',
        totalProductsSold: 'Total Products Sold',
        totalProducts: 'Total Products',
        totalCustomers: 'Total Customers',
        welcome: 'Welcome,',
        totalEnrollments: 'Total Enrollments',
        totalRevenue: 'Total Revenue',
        totalStock: 'Total Stock',
        productSalesVsStock: 'Product Sales vs Stock',
        courseEnrollments: 'Course Enrollments',
        createProduct: 'Create Product',
        enrollmentSuccessful: 'Enrollment Successful!',
        enrollementFailed: 'Enrollment Failed. Please try again.',
        enrollmentSuccessMessage: 'You have successfully enrolled in the course. Happy learning!',
        enrollmentFailMessage: 'There was an issue with the payment.',
        goToEnrolledCourses: 'Go to Enrolled Courses',
        startDate: 'Start Date',
        endDate: 'End Date',
        noStudentsFound: 'No students have enrolled in this course yet.',
        feePaid: 'Fee Paid',
        enrollmentAt: 'Enrollment At',
        addCourseMaterial: 'Add Course Material',
        viewEnrollments: 'View Enrollments',
        add: 'Add',
        noMaterialFound: 'No materials have been shared yet.',
        confirmDelete: 'Confirm Delete',
        deleteConfirmation: 'Are you sure you want to delete ',
        editCourse: 'Edit Course',
        courseTitle: "Course Title",
        enterCourseTitle: "Enter the course title",
        courseFee: "Course Fee",
        enterCourseFee: "Enter the course fee",
        category: "Category",
        selectCategory: "Select a category",
        courseDescription: "Description",
        enterCourseDescription: "Enter the course description",
        startDate: "Start Date",
        enterStartDate: "Enter the start date",
        endDate: "End Date",
        enterEndDate: "Enter the end date",
        uploadThumbnail: "Upload Thumbnail",
        thumbnailPreview: "Thumbnail Preview",
        noThumbnailUploaded: "No Thumbnail Uploaded",
        cancel: "Cancel",
        update: "Update",
        createCourse: "Create Course",
        courseTitle: "Course Title",
        enterCourseTitle: "Enter the course title",
        courseFee: "Course Fee",
        enterCourseFee: "Enter the course fee",
        category: "Category",
        selectCategory: "Select a category",
        courseDescription: "Description",
        enterCourseDescription: "Enter the course description",
        startDate: "Start Date",
        enterStartDate: "Enter the start date",
        endDate: "End Date",
        enterEndDate: "Enter the end date",
        uploadThumbnail: "Upload Thumbnail",
        thumbnailPreview: "Thumbnail Preview",
        noThumbnailUploaded: "No Thumbnail Uploaded",
        uploadedThumbnail: "Uploaded Thumbnail",
        cancel: "Cancel",
        create: "Create",
        createProduct: "Create Product",
        productName: "Product Name",
        enterProductName: "Enter the product name",
        description: "Description",
        enterProductDescription: "Enter the product description",
        price: "Price",
        enterProductPrice: "Enter the product price",
        category: "Category",
        selectCategory: "Select a category",
        stockQuantity: "Stock Quantity",
        enterStockQuantity: "Enter the stock quantity",
        uploadImages: "Upload Images (1 to 4)",
        uploadedImage: "Uploaded Image",
        cancel: "Cancel",
        create: "Create",
        "editProduct": "Edit Product",
        "productName": "Product Name",
        "enterProductName": "Enter the product name",
        "description": "Description",
        "enterProductDescription": "Enter the product description",
        "price": "Price",
        "enterProductPrice": "Enter the product price",
        "category": "Category",
        "selectCategory": "Select a category",
        "stockQuantity": "Stock Quantity",
        "enterStockQuantity": "Enter the stock quantity",
        "uploadImages": "Upload Images (1 to 4)",
        "uploadedImage": "Uploaded Image",
        "cancel": "Cancel",
        "save": "Save"
    },
    ur: {
        websiteName: "کاؤنٹری رائز",
        dashboard: "ڈیش بورڈ",
        products: "مصنوعات",
        product: 'پروڈکٹ',
        price: 'قیمت',
        salesOverview: "سیلز کا جائزہ",
        myCourses: "میرے کورسز",
        enrolledCourses: "داخل شدہ کورسز",
        exploreCourses: "کورسز دریافت کریں",
        offeredCourses: 'پیش کردہ کورسز',
        accountSettings: "اکاؤنٹ کی ترتیبات",
        signOut: "لاگ آؤٹ",
        profile: "پروفائل",
        editProfile: "پروفائل میں ترمیم کریں",
        saveChanges: "تبدیلیاں محفوظ کریں",
        cancel: "منسوخ کریں",
        delete: 'حذف کریں',
        edit: 'ترمیم کریں',
        profileNoFileChosen: "کوئی فائل منتخب نہیں کی گئی",
        personalInformation: "ذاتی معلومات",
        name: "نام",
        phone: "فون",
        email: "ای میل",
        addressInformation: "پتہ کی معلومات",
        address: "پتہ",
        province: "صوبہ",
        city: "شہر",
        noCourseFound: 'کوئی کورس نہیں ملا۔',
        searchCourseByTitle: 'عنوان کے ذریعے کورس تلاش کریں...',
        createCourse: 'کورس بنائیں',
        deleteCourseConfirmation: 'کیا آپ واقعی کورس کو حذف کرنا چاہتے ہیں',
        totalSales: 'کل فروخت',
        totalReviews: 'کل جائزے',
        rating: 'درجہ بندی',
        averageRating: 'اوسط درجہ بندی',
        mostSoldProduct: 'سب سے زیادہ فروخت ہونے والی پروڈکٹ',
        revenueGenerated: 'حاصل شدہ آمدنی',
        totalProductsSold: 'کل فروخت شدہ پروڈکٹس',
        totalProducts: 'کل پروڈکٹس',
        totalCustomers: 'کل صارفین',
        welcome: 'خوش آمدید،',
        totalEnrollments: 'کل انرولمنٹس',
        totalRevenue: 'کل آمدنی',
        totalStock: 'کل اسٹاک',
        productSalesVsStock: 'پروڈکٹ فروخت بمقابلہ اسٹاک',
        courseEnrollments: 'کورس انرولمنٹس',
        createProduct: 'Create Product',
        createProduct: 'پروڈکٹ بنائیں',
        enrollmentSuccessful: 'داخلہ کامیاب!',
        enrollmentFailed: 'داخلہ ناکام۔ براہ کرم دوبارہ کوشش کریں۔',
        enrollmentSuccessMessage: 'آپ نے کورس میں کامیابی سے داخلہ لیا ہے۔ خوشگوار تعلیم!',
        enrollmentFailMessage: 'ادائیگی میں کوئی مسئلہ تھا۔',
        goToEnrolledCourses: 'داخل شدہ کورسز پر جائیں',
        startDate: 'تاریخ آغاز',
        endDate: 'اختتامی تاریخ',
        noStudentsFound: 'اس کورس میں ابھی تک کوئی طالب علم داخل نہیں ہوا۔',
        feePaid: 'ادا کی گئی فیس',
        enrollmentAt: 'داخلے کی تاریخ',
        addCourseMaterial: 'کورس کا مواد شامل کریں',
        viewEnrollments: 'داخلے دیکھیں',
        add: 'شامل کریں',
        noMaterialFound: 'ابھی تک کوئی مواد شیئر نہیں کیا گیا۔',
        confirmDelete: 'حذف کی تصدیق',
        deleteConfirmation: 'کیا آپ واقعی حذف کرنا چاہتے ہیں؟',
        editCourse: "کورس ایڈیٹ کریں",
        courseTitle: "کورس کا عنوان",
        enterCourseTitle: "کورس کا عنوان درج کریں",
        courseFee: "کورس کی فیس",
        enterCourseFee: "کورس کی فیس درج کریں",
        category: "زمرہ",
        selectCategory: "زمرہ منتخب کریں",
        courseDescription: "تفصیل",
        enterCourseDescription: "کورس کی تفصیل درج کریں",
        startDate: "آغاز کی تاریخ",
        enterStartDate: "آغاز کی تاریخ درج کریں",
        endDate: "اختتام کی تاریخ",
        enterEndDate: "اختتام کی تاریخ درج کریں",
        uploadThumbnail: "تھمب نیل اپ لوڈ کریں",
        thumbnailPreview: "تھمب نیل کی پیش نظارہ",
        noThumbnailUploaded: "کوئی تھمب نیل اپ لوڈ نہیں کی گئی",
        cancel: "منسوخ کریں",
        update: "اپ ڈیٹ کریں",
        createCourse: "کورس تخلیق کریں",
        courseTitle: "کورس کا عنوان",
        enterCourseTitle: "کورس کا عنوان درج کریں",
        courseFee: "کورس کی فیس",
        enterCourseFee: "کورس کی فیس درج کریں",
        category: "زمرہ",
        selectCategory: "زمرہ منتخب کریں",
        courseDescription: "تفصیل",
        enterCourseDescription: "کورس کی تفصیل درج کریں",
        startDate: "آغاز کی تاریخ",
        enterStartDate: "آغاز کی تاریخ درج کریں",
        endDate: "اختتام کی تاریخ",
        enterEndDate: "اختتام کی تاریخ درج کریں",
        uploadThumbnail: "تھمب نیل اپ لوڈ کریں",
        thumbnailPreview: "تھمب نیل کی پیش نظارہ",
        noThumbnailUploaded: "کوئی تھمب نیل اپ لوڈ نہیں کی گئی",
        uploadedThumbnail: "اپ لوڈ شدہ تھمب نیل",
        cancel: "منسوخ کریں",
        create: "تخلیق کریں",
        createProduct: "پروڈکٹ تخلیق کریں",
        productName: "پروڈکٹ کا نام",
        enterProductName: "پروڈکٹ کا نام درج کریں",
        description: "تفصیل",
        enterProductDescription: "پروڈکٹ کی تفصیل درج کریں",
        price: "قیمت",
        enterProductPrice: "پروڈکٹ کی قیمت درج کریں",
        category: "زمرہ",
        selectCategory: "زمرہ منتخب کریں",
        stockQuantity: "اسٹاک کی مقدار",
        enterStockQuantity: "اسٹاک کی مقدار درج کریں",
        uploadImages: "تصاویر اپ لوڈ کریں (1 سے 4)",
        uploadedImage: "اپ لوڈ کی گئی تصویر",
        cancel: "منسوخ کریں",
        create: "تخلیق کریں",
        "editProduct": "پروڈکٹ ایڈٹ کریں",
        "productName": "پروڈکٹ کا نام",
        "enterProductName": "پروڈکٹ کا نام درج کریں",
        "description": "تفصیل",
        "enterProductDescription": "پروڈکٹ کی تفصیل درج کریں",
        "price": "قیمت",
        "enterProductPrice": "پروڈکٹ کی قیمت درج کریں",
        "category": "زمرہ",
        "selectCategory": "زمرہ منتخب کریں",
        "stockQuantity": "اسٹاک کی مقدار",
        "enterStockQuantity": "اسٹاک کی مقدار درج کریں",
        "uploadImages": "تصاویر اپ لوڈ کریں (1 سے 4)",
        "uploadedImage": "اپ لوڈ کی گئی تصویر",
        "cancel": "منسوخ کریں",
        "save": "محفوظ کریں"
    },
    pashto:
    {
        "websiteName": "کاؤنٹری رائز",
        "dashboard": "ډشبورډ",
        "products": "محصولات",
        "product": "محصول",
        "price": "قیمت",
        "salesOverview": "د پلور لنډیز",
        "myCourses": "زما کورسونه",
        "enrolledCourses": "شامل شوي کورسونه",
        "exploreCourses": "کورسونه وګورئ",
        "offeredCourses": "وړاندیز شوي کورسونه",
        "accountSettings": "د حساب ترتیبات",
        "signOut": "وتل",
        "profile": "پروفایل",
        "editProfile": "پروفایل سمول",
        "saveChanges": "بدلونونه خوندي کړئ",
        "cancel": "لغوه کول",
        "delete": "ړنګول",
        "edit": "سمول",
        "profileNoFileChosen": "هیڅ فایل ندی غوره شوی",
        "personalInformation": "شخصي معلومات",
        "name": "نوم",
        "phone": "ټیلفون",
        "email": "بریښنالیک",
        "addressInformation": "د پته معلومات",
        "address": "پته",
        "province": "ولایت",
        "city": "ښار",
        "noCourseFound": "هیڅ کورس ونه موندل شو.",
        "searchCourseByTitle": "د کورس عنوان له مخې لټون وکړئ...",
        "createCourse": "کورس جوړ کړئ",
        "deleteCourseConfirmation": "تاسو ډاډه یاست چې کورس حذف کړئ",
        "totalSales": "ټول پلور",
        "totalReviews": "ټولې بیاکتنې",
        "rating": "درجه بندي",
        "averageRating": "اوسط درجه بندي",
        "mostSoldProduct": "ترټولو ډیر پلورل شوی محصول",
        "revenueGenerated": "تولید شوی عاید",
        "totalProductsSold": "ټول پلورل شوي محصولات",
        "totalProducts": "ټول محصولات",
        "totalCustomers": "ټول پیرودونکي",
        "welcome": "ښه راغلاست,",
        "totalEnrollments": "ټولې نوم لیکنې",
        "totalRevenue": "ټول عاید",
        "totalStock": "ټول ذخیره",
        "productSalesVsStock": "د محصول پلور vs ذخیره",
        "courseEnrollments": "د کورس نوم لیکنې",
        "createProduct": "محصول جوړ کړئ",
        "enrollmentSuccessful": "شمولیت بریالی شو!",
        "enrollmentFailed": "شمولیت ناکام شو. مهرباني وکړئ بیا هڅه وکړئ.",
        "enrollmentSuccessMessage": "تاسو په بریالیتوب سره په کورس کې شامل شوئ. خوشاله زده کړه وکړئ!",
        "enrollmentFailMessage": "د تادیې سره ستونزه وه.",
        "goToEnrolledCourses": "شامل شوي کورسونو ته لاړ شئ",
        "startDate": "د پیل نیټه",
        "endDate": "د پای نیټه",
        "noStudentsFound": "په دې کورس کې هیڅ زده کوونکي شامل نه دي شوي.",
        "feePaid": "ورکړل شوی فیس",
        "enrollmentAt": "د نوم لیکنې نیټه",
        "addCourseMaterial": "د کورس مواد اضافه کړئ",
        "viewEnrollments": "شمولیتونه وګورئ",
        "add": "اضافه کړئ",
        "noMaterialFound": "هیڅ مواد نه دي شریک شوي.",
        "confirmDelete": "د حذف تصدیق",
        "deleteConfirmation": "تاسو ډاډه یاست چې حذف کړئ ",
        "editCourse": "کورس سمون وکړئ",
        "courseTitle": "د کورس سرلیک",
        "enterCourseTitle": "د کورس سرلیک دننه کړئ",
        "courseFee": "د کورس فیس",
        "enterCourseFee": "د کورس فیس دننه کړئ",
        "category": "کتګورۍ",
        "selectCategory": "کتګورۍ وټاکئ",
        "courseDescription": "تفصیل",
        "enterCourseDescription": "د کورس تفصیل دننه کړئ",
        "startDate": "د پیل نېټه",
        "enterStartDate": "د پیل نېټه دننه کړئ",
        "endDate": "د پای نېټه",
        "enterEndDate": "د پای نېټه دننه کړئ",
        "uploadThumbnail": "تھمب نیل اپلوډ کړئ",
        "thumbnailPreview": "تھمب نیل پیش نظارہ",
        "noThumbnailUploaded": "هیڅ تھمب نیل اپلوډ نه شوه",
        "cancel": "منسوخ کړئ",
        "update": "نوی کړئ",
        createCourse: "کورس جوړ کړئ",
        courseTitle: "د کورس سرلیک",
        enterCourseTitle: "د کورس سرلیک دننه کړئ",
        courseFee: "د کورس فیس",
        enterCourseFee: "د کورس فیس دننه کړئ",
        category: "کتګورۍ",
        selectCategory: "کتګورۍ وټاکئ",
        courseDescription: "تفصیل",
        enterCourseDescription: "د کورس تفصیل دننه کړئ",
        startDate: "د پیل نېټه",
        enterStartDate: "د پیل نېټه دننه کړئ",
        endDate: "د پای نېټه",
        enterEndDate: "د پای نېټه دننه کړئ",
        uploadThumbnail: "تھمب نیل اپلوډ کړئ",
        thumbnailPreview: "تھمب نیل پیش نظارہ",
        noThumbnailUploaded: "هیڅ تھمب نیل اپلوډ نه شوه",
        uploadedThumbnail: "اپلوډ شوی تھمب نیل",
        cancel: "منسوخ کړئ",
        create: "جوړ کړئ",
        createProduct: "محصول جوړ کړئ",
        productName: "د محصول نوم",
        enterProductName: "د محصول نوم دننه کړئ",
        description: "تفصیل",
        enterProductDescription: "د محصول تفصیل دننه کړئ",
        price: "بیه",
        enterProductPrice: "د محصول بیه دننه کړئ",
        category: "کتګورۍ",
        selectCategory: "کتګورۍ وټاکئ",
        stockQuantity: "د ذخیره مقدار",
        enterStockQuantity: "د ذخیره مقدار دننه کړئ",
        uploadImages: "انځورونه اپلوډ کړئ (1 څخه تر 4)",
        uploadedImage: "اپلوډ شوی انځور",
        cancel: "منسوخ کړئ",
        create: "جوړ کړئ",
        "editProduct": "محصول سمول",
        "productName": "د محصول نوم",
        "enterProductName": "د محصول نوم دننه کړئ",
        "description": "تفصیل",
        "enterProductDescription": "د محصول تفصیل دننه کړئ",
        "price": "بیه",
        "enterProductPrice": "د محصول بیه دننه کړئ",
        "category": "کتګورۍ",
        "selectCategory": "کتګورۍ وټاکئ",
        "stockQuantity": "د ذخیره مقدار",
        "enterStockQuantity": "د ذخیره مقدار دننه کړئ",
        "uploadImages": "انځورونه اپلوډ کړئ (1 څخه تر 4)",
        "uploadedImage": "اپلوډ شوی انځور",
        "cancel": "منسوخ کړئ",
        "save": "ساتل"

    },
    panjabi: {
        "websiteName": "کاؤنٹری رائز",
        "dashboard": "ڈیش بورڈ",
        "products": "مصنوعات",
        "product": "مصنوعہ",
        "price": "قیمت",
        "salesOverview": "سیلز دا جائیزہ",
        "myCourses": "میرے کورسز",
        "enrolledCourses": "شامل کردہ کورسز",
        "exploreCourses": "کورسز دَیکھو",
        "offeredCourses": "پیش کردہ کورسز",
        "accountSettings": "اکاؤنٹ دیاں ترتیبات",
        "signOut": "لاگ آؤٹ",
        "profile": "پروفائل",
        "editProfile": "پروفائل نوں ایڈیٹ کرو",
        "saveChanges": "تبدیلیاں محفوظ کرو",
        "cancel": "منسوخ کرو",
        "delete": "حذف کرو",
        "edit": "ایڈیٹ کرو",
        "profileNoFileChosen": "کوئی فائل منتخب نہیں کیتی",
        "personalInformation": "ذاتی معلومات",
        "name": "نام",
        "phone": "فون",
        "email": "ای میل",
        "addressInformation": "پتے دی معلومات",
        "address": "پتہ",
        "province": "صوبہ",
        "city": "شہر",
        "noCourseFound": "کوئی کورس نہیں ملا",
        "searchCourseByTitle": "کورس دا عنوان نال تلاش کرو...",
        "createCourse": "کورس بناؤ",
        "deleteCourseConfirmation": "کیا تُسیں کورس حذف کرنا چاندے او؟",
        "totalSales": "کل سیلز",
        "totalReviews": "کل جائزے",
        "rating": "ریٹنگ",
        "averageRating": "اوسط ریٹنگ",
        "mostSoldProduct": "سب توں زیادہ بیچی گئی مصنوعات",
        "revenueGenerated": "پیدا کیتی گئی آمدنی",
        "totalProductsSold": "کل بیچی گئی مصنوعات",
        "totalProducts": "کل مصنوعات",
        "totalCustomers": "کل گاہک",
        "welcome": "خوش آمدید،",
        "totalEnrollments": "کل اندراجات",
        "totalRevenue": "کل آمدنی",
        "totalStock": "کل اسٹاک",
        "productSalesVsStock": "مصنوعات دیاں سیلز بمقابلہ اسٹاک",
        "courseEnrollments": "کورس دیاں اندراجات",
        "createProduct": "مصنوعہ بناؤ",
        "enrollmentSuccessful": "اندراج کامیاب!",
        "enrollmentFailed": "اندراج ناکام ہوگیا۔ مہربانی کرکے دوبارہ کوشش کرو",
        "enrollmentSuccessMessage": "تُسیں کامیابی نال کورس وچ شامل ہوگئے او۔ خوشگوار سیکھائی!",
        "enrollmentFailMessage": "ادائیگی وچ کوئی مسئلہ آیا",
        "goToEnrolledCourses": "شامل کردہ کورسز تے جاؤ",
        "startDate": "شروع ہونے دی تاریخ",
        "endDate": "اختتام دی تاریخ",
        "noStudentsFound": "اس کورس وچ ہن تک کوئی طالب علم شامل نہیں ہویا",
        "feePaid": "فیس ادا کیتی گئی",
        "enrollmentAt": "اندراج دی تاریخ",
        "addCourseMaterial": "کورس دا مواد شامل کرو",
        "viewEnrollments": "اندراجات دیکھو",
        "add": "شامل کرو",
        "noMaterialFound": "کوئی مواد شیئر نہیں کیتا گیا",
        "confirmDelete": "حذف دی تصدیق کرو",
        "deleteConfirmation": "کیا تُسیں واقعی حذف کرنا چاندے او؟",
        "editCourse": "کورس ایڈیٹ کرو",
        "courseTitle": "کورس دا عنوان",
        "enterCourseTitle": "کورس دا عنوان داخل کرو",
        "courseFee": "کورس دی فیس",
        "enterCourseFee": "کورس دی فیس داخل کرو",
        "category": "زمرہ",
        "selectCategory": "زمرہ منتخب کرو",
        "courseDescription": "تفصیل",
        "enterCourseDescription": "کورس دی تفصیل داخل کرو",
        "startDate": "شروع ہونے دی تاریخ",
        "enterStartDate": "شروع ہونے دی تاریخ داخل کرو",
        "endDate": "اختتام دی تاریخ",
        "enterEndDate": "اختتام دی تاریخ داخل کرو",
        "uploadThumbnail": "تھمب نیل اپ لوڈ کرو",
        "thumbnailPreview": "تھمب نیل دی پیش نظارہ",
        "noThumbnailUploaded": "کوئی تھمب نیل اپ لوڈ نہیں کیتی گئی",
        "cancel": "منسوخ کرو",
        "update": "اپ ڈیٹ کرو",
        createCourse: "کورس تخلیق کرو",
        courseTitle: "کورس دا عنوان",
        enterCourseTitle: "کورس دا عنوان داخل کرو",
        courseFee: "کورس دی فیس",
        enterCourseFee: "کورس دی فیس داخل کرو",
        category: "زمرہ",
        selectCategory: "زمرہ منتخب کرو",
        courseDescription: "تفصیل",
        enterCourseDescription: "کورس دی تفصیل داخل کرو",
        startDate: "شروع ہونے دی تاریخ",
        enterStartDate: "شروع ہونے دی تاریخ داخل کرو",
        endDate: "اختتام دی تاریخ",
        enterEndDate: "اختتام دی تاریخ داخل کرو",
        uploadThumbnail: "تھمب نیل اپ لوڈ کرو",
        thumbnailPreview: "تھمب نیل دی پیش نظارہ",
        noThumbnailUploaded: "کوئی تھمب نیل اپ لوڈ نہیں کیتی گئی",
        uploadedThumbnail: "اپ لوڈ کیتی تھمب نیل",
        cancel: "منسوخ کرو",
        create: "تخلیق کرو",
        createProduct: "پروڈکٹ تخلیق کرو",
        productName: "پروڈکٹ دا ناں",
        enterProductName: "پروڈکٹ دا ناں داخل کرو",
        description: "تفصیل",
        enterProductDescription: "پروڈکٹ دی تفصیل داخل کرو",
        price: "قیمت",
        enterProductPrice: "پروڈکٹ دی قیمت داخل کرو",
        category: "زمرہ",
        selectCategory: "زمرہ منتخب کرو",
        stockQuantity: "اسٹاک دی مقدار",
        enterStockQuantity: "اسٹاک دی مقدار داخل کرو",
        uploadImages: "تصاویر اپ لوڈ کرو (1 توں 4)",
        uploadedImage: "اپ لوڈ کیتی گئی تصویر",
        cancel: "منسوخ کرو",
        create: "تخلیق کرو",
        "editProduct": "پروڈکٹ ایڈٹ کرو",
        "productName": "پروڈکٹ دا ناں",
        "enterProductName": "پروڈکٹ دا ناں داخل کرو",
        "description": "تفصیل",
        "enterProductDescription": "پروڈکٹ دی تفصیل داخل کرو",
        "price": "قیمت",
        "enterProductPrice": "پروڈکٹ دی قیمت داخل کرو",
        "category": "زمرہ",
        "selectCategory": "زمرہ منتخب کرو",
        "stockQuantity": "اسٹاک دی مقدار",
        "enterStockQuantity": "اسٹاک دی مقدار داخل کرو",
        "uploadImages": "تصاویر اپ لوڈ کرو (1 توں 4)",
        "uploadedImage": "اپ لوڈ کیتی گئی تصویر",
        "cancel": "منسوخ کرو",
        "save": "محفوظ کرو"
    }
};
