import "./globals.css";
import { AuthProvider } from "./AuthProvider";

export const metadata = {
  title: "EmpowerHer Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
